In [3]:
!uv add mlflow optuna scikit-learn

Resolved 235 packages in 1.05s
Prepared 1 package in 164ms
Installed 2 packages in 17ms
 + colorlog==6.12.0
 + optuna==4.9.0

In [63]:
import mlflow

# Connect to remote MLflow server
mlflow.set_tracking_uri("http://localhost:5000")

In [5]:
!uv add pandas numpy matplotlib

Resolved 235 packages in 148ms
Checked 229 packages in 7ms

In [6]:
import pandas as pd

In [7]:
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

In [9]:
pwd

'/home/butcher/projects/llm_wiki/experiments'

In [86]:
df = pd.read_csv('/home/butcher/projects/llm_wiki/experiments/train.csv')

In [87]:
df.head(10)

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
5,1859,0,0.5,1,3,0,22,0.7,164,1,...,1004,1654,1067,17,1,10,1,0,0,1
6,1821,0,1.7,0,4,1,10,0.8,139,8,...,381,1018,3220,13,8,18,1,0,1,3
7,1954,0,0.5,1,0,0,24,0.8,187,4,...,512,1149,700,16,3,5,1,1,1,0
8,1445,1,0.5,0,0,0,53,0.7,174,7,...,386,836,1099,17,1,20,1,0,0,0
9,509,1,0.6,1,2,1,9,0.1,93,5,...,1137,1224,513,19,10,12,1,0,0,0

In [88]:
df.describe()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
count,2000.000000,2000.0000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,...,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1238.518500,0.4950,1.522250,0.509500,4.309500,0.521500,32.046500,0.501750,140.249000,4.520500,...,645.108000,1251.515500,2124.213000,12.306500,5.767000,11.011000,0.761500,0.503000,0.507000,1.500000
std,439.418206,0.5001,0.816004,0.500035,4.341444,0.499662,18.145715,0.288416,35.399655,2.287837,...,443.780811,432.199447,1084.732044,4.213245,4.356398,5.463955,0.426273,0.500116,0.500076,1.118314
min,501.000000,0.0000,0.500000,0.000000,0.000000,0.000000,2.000000,0.100000,80.000000,1.000000,...,0.000000,500.000000,256.000000,5.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000
25%,851.750000,0.0000,0.700000,0.000000,1.000000,0.000000,16.000000,0.200000,109.000000,3.000000,...,282.750000,874.750000,1207.500000,9.000000,2.000000,6.000000,1.000000,0.000000,0.000000,0.750000
50%,1226.000000,0.0000,1.500000,1.000000,3.000000,1.000000,32.000000,0.500000,141.000000,4.000000,...,564.000000,1247.000000,2146.500000,12.000000,5.000000,11.000000,1.000000,1.000000,1.000000,1.500000
75%,1615.250000,1.0000,2.200000,1.000000,7.000000,1.000000,48.000000,0.800000,170.000000,7.000000,...,947.250000,1633.000000,3064.500000,16.000000,9.000000,16.000000,1.000000,1.000000,1.000000,2.250000
max,1998.000000,1.0000,3.000000,1.000000,19.000000,1.000000,64.000000,1.000000,200.000000,8.000000,...,1960.000000,1998.000000,3998.000000,19.000000,18.000000,20.000000,1.000000,1.000000,1.000000,3.000000

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  2000 non-null   int64
 1   blue           2000 non-null   int64
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64
 4   fc             2000 non-null   int64
 5   four_g         2000 non-null   int64
 6   int_memory     2000 non-null   int64
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64
 9   n_cores        2000 non-null   int64
 10  pc             2000 non-null   int64
 11  px_height      2000 non-null   int64
 12  px_width       2000 non-null   int64
 13  ram            2000 non-null   int64
 14  sc_h           2000 non-null   int64
 15  sc_w           2000 non-null   int64
 16  talk_time      2000 non-null   int64
 17  three_g        2000 non-null   int64
 18  touch_screen   2000 non-null   int64
 19  wifi           2000 non-null   int64
 20  price_range    2000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 328.3 KB

In [90]:
df['price_range'].value_counts()

price_range
1    500
2    500
3    500
0    500
Name: count, dtype: int64

In [91]:
df.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='object')

In [92]:
from sklearn.model_selection import train_test_split
X, y = df.iloc[:, :-1],df.iloc[:,-1]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [93]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()


X_train_scaled = scaler.fit_transform(X_train)

In [94]:
X_train_scaled

array([[ 1.38919326,  1.011314  , -1.25918898, ..., -1.78870765,
        -1.00878862, -1.02532046],
       [ 0.07840603,  1.011314  , -1.25918898, ..., -1.78870765,
        -1.00878862,  0.97530483],
       [-1.02457347, -0.98881258,  1.18747125, ...,  0.55906285,
         0.99128795,  0.97530483],
       ...,
       [ 1.10374308, -0.98881258,  0.5758062 , ...,  0.55906285,
         0.99128795,  0.97530483],
       [-1.21867959,  1.011314  ,  1.43213728, ...,  0.55906285,
        -1.00878862, -1.02532046],
       [-0.39429947, -0.98881258,  1.6768033 , ...,  0.55906285,
        -1.00878862, -1.02532046]], shape=(1600, 20))

In [95]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(random_state=42, solver="lbfgs")

In [96]:
y_train

469     1
565     0
396     3
452     3
325     0
       ..
1170    0
100     3
63      2
180     0
876     0
Name: price_range, Length: 1600, dtype: int64

In [97]:
model.fit(X_train_scaled, y_train)

2026/08/27 02:52:58 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'b2f8c8e49b3b4526b5b290f5bc041580', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow
2026/08/27 02:52:58 WARNING mlflow.sklearn: Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'flatten'
2026/08/27 02:52:59 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/08/27 02:53:01 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.

🏃 View run enthused-dove-613 at: http://localhost:5000/#/experiments/2/runs/b2f8c8e49b3b4526b5b290f5bc041580
🧪 View experiment at: http://localhost:5000/#/experiments/2

LogisticRegression(random_state=42)

In [98]:
X_test_scaled = scaler.transform(X_test)

In [99]:
y_pred = model.predict(X_test_scaled)

In [100]:
y_pred

array([3, 1, 0, 2, 3, 2, 0, 0, 1, 0, 3, 0, 0, 1, 3, 3, 2, 0, 1, 3, 1, 0,
       3, 2, 2, 1, 1, 0, 2, 1, 1, 2, 0, 2, 2, 3, 0, 3, 1, 0, 2, 0, 0, 2,
       3, 0, 3, 3, 2, 1, 0, 3, 0, 2, 0, 3, 3, 0, 2, 1, 1, 2, 3, 1, 0, 1,
       0, 1, 3, 3, 3, 2, 1, 1, 2, 0, 3, 3, 1, 3, 3, 2, 2, 0, 0, 1, 0, 0,
       0, 0, 0, 2, 2, 3, 0, 3, 0, 0, 2, 2, 3, 1, 1, 0, 3, 3, 1, 2, 1, 1,
       0, 2, 3, 1, 3, 2, 2, 2, 2, 2, 2, 0, 3, 0, 3, 3, 2, 0, 2, 3, 3, 0,
       0, 1, 3, 1, 2, 3, 2, 3, 3, 3, 2, 1, 3, 2, 1, 1, 0, 1, 3, 0, 1, 1,
       3, 3, 3, 2, 0, 2, 2, 0, 0, 3, 1, 1, 3, 2, 3, 0, 1, 1, 1, 3, 2, 1,
       1, 3, 0, 3, 2, 2, 2, 3, 0, 2, 0, 1, 1, 1, 0, 2, 1, 2, 3, 0, 2, 3,
       1, 1, 1, 2, 1, 2, 0, 0, 3, 1, 1, 2, 1, 3, 2, 0, 0, 3, 1, 2, 3, 3,
       0, 3, 3, 2, 2, 1, 1, 2, 1, 1, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 3,
       0, 1, 3, 2, 2, 3, 3, 2, 1, 0, 3, 3, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1,
       0, 0, 3, 1, 2, 3, 3, 0, 0, 0, 1, 3, 2, 2, 3, 1, 3, 2, 2, 1, 1, 0,
       1, 1, 1, 3, 1, 0, 3, 1, 1, 1, 0, 1, 1, 1, 1, 3, 0, 3, 2, 3, 1, 2,
       1, 2, 0, 0, 2, 3, 3, 2, 3, 1, 0, 2, 0, 2, 3, 3, 0, 0, 3, 2, 0, 1,
       1, 0, 0, 0, 0, 0, 3, 1, 3, 0, 1, 2, 3, 2, 3, 0, 2, 1, 2, 3, 3, 0,
       2, 3, 1, 0, 0, 1, 2, 3, 3, 1, 1, 0, 3, 3, 3, 1, 2, 1, 1, 0, 0, 3,
       1, 0, 0, 0, 3, 1, 1, 2, 0, 3, 0, 3, 2, 3, 2, 2, 0, 1, 1, 1, 0, 1,
       2, 1, 2, 2])

In [101]:
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    recall_score,
)

In [102]:
accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")

# 2. Complete Summary Report (Precision, Recall, F1-Score per class)
print("\n--- Classification Report ---")
print(classification_report(y_test, y_pred))

# 3. Confusion Matrix
print("\n--- Confusion Matrix ---")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9650

--- Classification Report ---
              precision    recall  f1-score   support

           0       0.99      0.98      0.98       100
           1       0.96      0.96      0.96       100
           2       0.95      0.94      0.94       100
           3       0.96      0.98      0.97       100

    accuracy                           0.96       400
   macro avg       0.97      0.96      0.96       400
weighted avg       0.97      0.96      0.96       400


--- Confusion Matrix ---
[[98  2  0  0]
 [ 1 96  3  0]
 [ 0  2 94  4]
 [ 0  0  2 98]]

In [55]:
from sklearn.model_selection import GridSearchCV

In [56]:
param_grid = {
    "C": [0.01, 0.1, 1, 10],
    "penalty": ["l1", "l2"],
}

# 2. Setup GridSearchCV (5-fold cross-validation)
grid_search = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=5,  # 5-fold CV
    scoring="accuracy",  # metric: 'accuracy', 'recall', 'roc_auc', 'f1'
    n_jobs=-1,  # use all CPU cores
    verbose=1,
)

# 3. Fit on scaled training data
grid_search.fit(X_train_scaled, y_train)

# 4. View best results
print("Best Parameters:", grid_search.best_params_)
print("Best CV Score:  ", grid_search.best_score_)

# 5. Make predictions using the best model automatically
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test_scaled)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/butcher/projects/llm_wiki/.venv/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:489: FitFailedWarning:
20 fits failed out of a total of 40.

Best Parameters: {'C': 10, 'penalty': 'l2'}
Best CV Score:   0.95875

In [57]:
!uv add xgboost

Resolved 237 packages in 1.11s
Prepared 2 packages in 3.37s
Installed 2 packages in 6ms
 + nvidia-nccl-cu13==2.31.2
 + xgboost==3.4.1

In [64]:
import mlflow
import mlflow.sklearn
import mlflow.xgboost
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from xgboost import XGBClassifier

# Create or target a named experiment
mlflow.set_experiment("Classifier_Comparison_Experiment")

# Generate sample dataset
X, y = make_classification(
    n_samples=1000, n_features=20, n_informative=10, random_state=42
)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

2026/08/27 02:14:26 INFO mlflow.tracking.fluent: Experiment with name 'Classifier_Comparison_Experiment' does not exist. Creating a new experiment.

In [109]:
def log_experiment(model, model_name, X_tr, X_te, y_tr, y_te, params, flavor):
    """Trains a model, logs parameters, metrics, and saves the artifact to MLflow."""
    with mlflow.start_run(run_name=model_name):
        # 1. Fit Model
        model.fit(X_tr, y_tr)
        y_pred = model.predict(X_te)

        # 2. Compute Metrics
        metrics = {
            "accuracy": accuracy_score(y_te, y_pred),
            "precision": precision_score(y_te, y_pred, average="weighted"),
            "recall": recall_score(y_te, y_pred, average="weighted"),
            "f1_score": f1_score(y_te, y_pred, average="weighted"),
        }

        # 3. Log Parameters, Metrics, & Tags to MLflow
        mlflow.log_params(params)
        mlflow.log_metrics(metrics)
        mlflow.set_tag("model_type", model_name)

        # 4. Log the Trained Model Artifact
        if flavor == "sklearn":
            mlflow.sklearn.log_model(model, artifact_path="model")
            return model
        elif flavor == "xgboost":
            mlflow.xgboost.log_model(model, artifact_path="model")
            return model


# --- 1. Logistic Regression ---
lr_params = {"C": 1.0, "penalty": "l2", "solver": "lbfgs"}
lr_model = LogisticRegression(**lr_params, random_state=42)
lr_model = log_experiment(
    lr_model,
    "LogisticRegression",
    X_train_scaled,
    X_test_scaled,
    y_train,
    y_test,
    lr_params,
    "sklearn",
)

# --- 2. Random Forest ---
rf_params = {"n_estimators": 100, "max_depth": 10, "criterion": "gini"}
rf_model = RandomForestClassifier(**rf_params, random_state=42)
rf_model = log_experiment(
    rf_model,
    "RandomForest",
    X_train,
    X_test,
    y_train,
    y_test,
    rf_params,
    "sklearn",
)

# --- 3. Support Vector Machine (SVM) ---
svm_params = {"C": 1.0, "kernel": "rbf", "gamma": "scale"}
svm_model = SVC(**svm_params, random_state=42)
svm_model = log_experiment(
    svm_model,
    "SVM",
    X_train_scaled,
    X_test_scaled,
    y_train,
    y_test,
    svm_params,
    "sklearn",
)

# --- 4. XGBoost ---
xgb_params = {
    "n_estimators": 100,
    "learning_rate": 0.1,
    "max_depth": 6,
    "eval_metric": "logloss",
}
xgb_model = XGBClassifier(**xgb_params, random_state=42)
xgb_model = log_experiment(
    xgb_model,
    "XGBoost",
    X_train,
    X_test,
    y_train,
    y_test,
    xgb_params,
    "xgboost",
)

2026/08/27 02:57:41 WARNING mlflow.sklearn: Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'flatten'
2026/08/27 02:57:41 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/08/27 02:57:44 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026/08/27 02:57:45 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/08/27 02:57:51 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.

🏃 View run LogisticRegression at: http://localhost:5000/#/experiments/2/runs/3b9cc6c8522e4b548fea8e0694820cc4
🧪 View experiment at: http://localhost:5000/#/experiments/2

2026/08/27 02:57:52 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/08/27 02:57:55 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026/08/27 02:57:56 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/08/27 02:58:02 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026/08/27 02:58:03 WARNING mlflow.sklearn: Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'flatten'

🏃 View run RandomForest at: http://localhost:5000/#/experiments/2/runs/1b640981dee64e038979aa029e0e5265
🧪 View experiment at: http://localhost:5000/#/experiments/2

2026/08/27 02:58:03 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/08/27 02:58:06 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026/08/27 02:58:07 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/08/27 02:58:14 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.

🏃 View run SVM at: http://localhost:5000/#/experiments/2/runs/6abba780c1d645608135073ca774df15
🧪 View experiment at: http://localhost:5000/#/experiments/2

2026/08/27 02:58:15 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/08/27 02:58:18 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026/08/27 02:58:19 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/08/27 02:58:22 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.

🏃 View run XGBoost at: http://localhost:5000/#/experiments/2/runs/a182eabc1f6b466bb64457ab3774baae
🧪 View experiment at: http://localhost:5000/#/experiments/2

In [66]:
import os
import warnings
import mlflow
import mlflow.sklearn
import mlflow.xgboost
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
)
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from xgboost import XGBClassifier

warnings.filterwarnings("ignore")

# ==========================================
# 1. SETUP MLFLOW TRACKING
# ==========================================
mlflow.set_tracking_uri("http://localhost:5000")
mlflow.set_experiment("Classification_GridSearch_CV5_Full_Tracking")

# Enable automatic logging for scikit-learn and XGBoost
# max_tuning_runs=500 ensures every single grid search combination is logged as a child run
mlflow.sklearn.autolog(max_tuning_runs=500, log_models=True)
mlflow.xgboost.autolog(log_models=True)

# ==========================================
# 2. GENERATE & PREPARE DATASET
# ==========================================
X, y = make_classification(
    n_samples=1000,
    n_features=20,
    n_informative=10,
    n_redundant=5,
    random_state=42,
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Standardize features (Required for Logistic Regression and SVM)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


# ==========================================
# 3. HELPER FUNCTION FOR TUNING & EVALUATION
# ==========================================
def run_grid_search_experiment(
    model, model_name, param_grid, X_tr, X_te, y_tr, y_te
):
    """Executes 5-Fold Cross-Validation Grid Search.

    MLflow autologging automatically records:
      - Parent Run: Holds overall grid search, best parameters, and best model artifact.
      - Child Runs: One run per hyperparameter combination evaluated during 5-fold CV.
    """
    print(f"\n==================================================")
    print(f" Running 5-Fold Grid Search for: {model_name}")
    print(f"==================================================")

    # Parent run context
    with mlflow.start_run(run_name=f"Parent_GridSearch_{model_name}"):
        mlflow.set_tag("model_family", model_name)
        mlflow.set_tag("cv_folds", 5)

        # Configure 5-Fold Cross Validation
        grid_search = GridSearchCV(
            estimator=model,
            param_grid=param_grid,
            cv=5,
            scoring="f1_weighted",
            n_jobs=-1,
            verbose=1,
        )

        # Fit Grid Search (Autolog creates child runs during execution)
        grid_search.fit(X_tr, y_tr)

        # Evaluate best model on test set
        best_model = grid_search.best_estimator_
        y_pred = best_model.predict(X_te)

        # Calculate holdout metrics
        test_metrics = {
            "test_accuracy": accuracy_score(y_te, y_pred),
            "test_precision": precision_score(y_te, y_pred, average="weighted"),
            "test_recall": recall_score(y_te, y_pred, average="weighted"),
            "test_f1_score": f1_score(y_te, y_pred, average="weighted"),
        }

        # Log holdout test metrics to the parent run
        mlflow.log_metrics(test_metrics)

        print(f" Best Parameters: {grid_search.best_params_}")
        print(f" Best CV F1 Score: {grid_search.best_score_:.4f}")
        print(f" Holdout Test F1 Score: {test_metrics['test_f1_score']:.4f}")

    return grid_search.best_estimator_


# ==========================================
# 4. MODEL TUNING PIPELINES
# ==========================================

# --- Model 1: Logistic Regression ---
lr_param_grid = {
    "C": [0.01, 0.1, 1.0, 10.0],
    "penalty": ["l1", "l2"],
    "solver": ["saga"],  # 'saga' supports both L1 and L2 penalties
}

best_lr = run_grid_search_experiment(
    model=LogisticRegression(random_state=42, max_iter=1000),
    model_name="LogisticRegression",
    param_grid=lr_param_grid,
    X_tr=X_train_scaled,
    X_te=X_test_scaled,
    y_tr=y_train,
    y_te=y_test,
)


# --- Model 2: Random Forest ---
rf_param_grid = {
    "n_estimators": [50, 100, 200],
    "max_depth": [5, 10, None],
    "criterion": ["gini", "entropy"],
}

best_rf = run_grid_search_experiment(
    model=RandomForestClassifier(random_state=42),
    model_name="RandomForest",
    param_grid=rf_param_grid,
    X_tr=X_train,
    X_te=X_test,
    y_tr=y_train,
    y_te=y_test,
)


# --- Model 3: Support Vector Machine (SVM) ---
svm_param_grid = {
    "C": [0.1, 1.0, 10.0],
    "kernel": ["rbf", "linear"],
    "gamma": ["scale", "auto"],
}

best_svm = run_grid_search_experiment(
    model=SVC(random_state=42),
    model_name="SVM",
    param_grid=svm_param_grid,
    X_tr=X_train_scaled,
    X_te=X_test_scaled,
    y_tr=y_train,
    y_te=y_test,
)


# --- Model 4: XGBoost ---
xgb_param_grid = {
    "n_estimators": [50, 100],
    "learning_rate": [0.01, 0.1, 0.2],
    "max_depth": [3, 6],
}

best_xgb = run_grid_search_experiment(
    model=XGBClassifier(eval_metric="logloss", random_state=42),
    model_name="XGBoost",
    param_grid=xgb_param_grid,
    X_tr=X_train,
    X_te=X_test,
    y_tr=y_train,
    y_te=y_test,
)

print("\n All hyperparameter tuning experiments successfully logged to MLflow!")

2026/08/27 02:34:09 INFO mlflow.tracking.fluent: Experiment with name 'Classification_GridSearch_CV5_Full_Tracking' does not exist. Creating a new experiment.

==================================================
 Running 5-Fold Grid Search for: LogisticRegression
==================================================
Fitting 5 folds for each of 8 candidates, totalling 40 fits

2026/08/27 02:34:12 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/08/27 02:34:15 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026/08/27 02:34:16 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/08/27 02:34:19 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026/08/27 02:34:19 INFO mlflow.sklearn.utils: Logging the 500 best runs, no runs will be omitted.

🏃 View run gaudy-seal-671 at: http://localhost:5000/#/experiments/2/runs/9b28567208754072a47c9cf62a475808
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run thoughtful-pig-998 at: http://localhost:5000/#/experiments/2/runs/67eacb2ed5c447d5af4e36107e2605fb
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run painted-penguin-648 at: http://localhost:5000/#/experiments/2/runs/71efc20b37904552b0799f0ed4ff1be6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run chill-lamb-582 at: http://localhost:5000/#/experiments/2/runs/354e060babb04f2793639908ba26d2f3
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run merciful-owl-798 at: http://localhost:5000/#/experiments/2/runs/3a6f9d9340c4408ab5bac70ac134500c
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run gifted-smelt-100 at: http://localhost:5000/#/experiments/2/runs/1e1fdcaadcbd46619d51cff2b6200663
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run brawny-jay-887 at: http://localhost:5000/#/experiments/2/runs/229eaa89fe594a9d966a6778881b6191
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run shivering-jay-67 at: http://localhost:5000/#/experiments/2/runs/01f06f0f626b4855ba581da321e2b391
🧪 View experiment at: http://localhost:5000/#/experiments/2
 Best Parameters: {'C': 0.1, 'penalty': 'l1', 'solver': 'saga'}
 Best CV F1 Score: 0.8510
 Holdout Test F1 Score: 0.8398
🏃 View run Parent_GridSearch_LogisticRegression at: http://localhost:5000/#/experiments/2/runs/e894f22b972546d99bdb6187fc4da3e5
🧪 View experiment at: http://localhost:5000/#/experiments/2

==================================================
 Running 5-Fold Grid Search for: RandomForest
==================================================
Fitting 5 folds for each of 18 candidates, totalling 90 fits

2026/08/27 02:34:26 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/08/27 02:34:29 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026/08/27 02:34:30 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/08/27 02:34:32 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026/08/27 02:34:33 INFO mlflow.sklearn.utils: Logging the 500 best runs, no runs will be omitted.

🏃 View run trusting-goose-518 at: http://localhost:5000/#/experiments/2/runs/4a2f3bfaa8964e69a6882fb8fa1e021f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run fortunate-fly-736 at: http://localhost:5000/#/experiments/2/runs/85d20bb88b25492a9b4eb545b427e404
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run luxuriant-newt-573 at: http://localhost:5000/#/experiments/2/runs/690ef6b1b941478bbab4a61cd6a488b9
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run fortunate-worm-809 at: http://localhost:5000/#/experiments/2/runs/5a64fdf5f273441788d93836fed8bf94
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run sincere-grub-304 at: http://localhost:5000/#/experiments/2/runs/a9cc18b299f847879ca1e4292702bea8
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run stylish-elk-18 at: http://localhost:5000/#/experiments/2/runs/978ad00f2d4b4207b3f667ae658c30d8
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run auspicious-pig-444 at: http://localhost:5000/#/experiments/2/runs/2c51cb0af5cd4d0a970337e6055595f7
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run capricious-mouse-907 at: http://localhost:5000/#/experiments/2/runs/43fc606dd42a48c0871c0b830718530f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run bold-mole-630 at: http://localhost:5000/#/experiments/2/runs/00bf2cca682e4924babad4550cc9e6f9
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run suave-owl-651 at: http://localhost:5000/#/experiments/2/runs/6b7bb8b60bb5410797a2224917f262df
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run sneaky-goose-384 at: http://localhost:5000/#/experiments/2/runs/176169d5880b4f1d9aedefc7a01fc162
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run shivering-mule-312 at: http://localhost:5000/#/experiments/2/runs/a7959e828f77428eb31f931caeec7324
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run auspicious-midge-514 at: http://localhost:5000/#/experiments/2/runs/ec822f72d3c4469b9d67e1ae53e1c752
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run respected-slug-392 at: http://localhost:5000/#/experiments/2/runs/c3cd80cc384e4f4eae062c494f60f2f8
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run agreeable-bee-103 at: http://localhost:5000/#/experiments/2/runs/89630f9c75624b72bdf4745d495a9550
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run upbeat-roo-729 at: http://localhost:5000/#/experiments/2/runs/a6e404feb6b9480abe2973c7a360903f
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run blushing-hog-135 at: http://localhost:5000/#/experiments/2/runs/b84d590a7fbe4b7da739c59dc441dffe
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run omniscient-crow-620 at: http://localhost:5000/#/experiments/2/runs/cd52cb8c9cbb4c4f83fc46e434ae9245
🧪 View experiment at: http://localhost:5000/#/experiments/2
 Best Parameters: {'criterion': 'gini', 'max_depth': None, 'n_estimators': 100}
 Best CV F1 Score: 0.9312
 Holdout Test F1 Score: 0.9099
🏃 View run Parent_GridSearch_RandomForest at: http://localhost:5000/#/experiments/2/runs/23fed12c13f04825803189e637f81c10
🧪 View experiment at: http://localhost:5000/#/experiments/2

==================================================
 Running 5-Fold Grid Search for: SVM
==================================================
Fitting 5 folds for each of 12 candidates, totalling 60 fits

2026/08/27 02:34:37 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/08/27 02:34:39 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026/08/27 02:34:41 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/08/27 02:34:43 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026/08/27 02:34:44 INFO mlflow.sklearn.utils: Logging the 500 best runs, no runs will be omitted.

🏃 View run adorable-horse-470 at: http://localhost:5000/#/experiments/2/runs/38f3fc153eb54b32baec7c867762ee56
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run resilient-goose-832 at: http://localhost:5000/#/experiments/2/runs/61ea251ab5b34f10914b7da2696c2ff8
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run luxuriant-owl-816 at: http://localhost:5000/#/experiments/2/runs/76fcde0efe354fd1b05a62dfb73560c6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run handsome-wolf-920 at: http://localhost:5000/#/experiments/2/runs/f4620aaeac6641fc92b22483c05be69a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run bedecked-hound-878 at: http://localhost:5000/#/experiments/2/runs/66dbb530218248aa850dce026abc41ff
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run defiant-squirrel-786 at: http://localhost:5000/#/experiments/2/runs/19560c5950e847ddb776c3a0113acae6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run secretive-stoat-390 at: http://localhost:5000/#/experiments/2/runs/cac26c944de64a06a7689b03aadebf01
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run inquisitive-fowl-192 at: http://localhost:5000/#/experiments/2/runs/37552069b75340d9ba5c794ad3910a96
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run learned-fish-100 at: http://localhost:5000/#/experiments/2/runs/2f680e21c60a495f81d6c9f71acefdf3
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run classy-bee-503 at: http://localhost:5000/#/experiments/2/runs/178fe0d8f1f249479f94b81557047314
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run capricious-wren-191 at: http://localhost:5000/#/experiments/2/runs/a58a8dd5015945008009197b9d063a17
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run loud-owl-678 at: http://localhost:5000/#/experiments/2/runs/941813b9252844fba1c4de3b48b452fe
🧪 View experiment at: http://localhost:5000/#/experiments/2
 Best Parameters: {'C': 10.0, 'gamma': 'auto', 'kernel': 'rbf'}
 Best CV F1 Score: 0.9425
 Holdout Test F1 Score: 0.9450
🏃 View run Parent_GridSearch_SVM at: http://localhost:5000/#/experiments/2/runs/6a913c38b0c842c0892ae32b13335b02
🧪 View experiment at: http://localhost:5000/#/experiments/2

==================================================
 Running 5-Fold Grid Search for: XGBoost
==================================================
Fitting 5 folds for each of 12 candidates, totalling 60 fits

2026/08/27 02:34:48 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/08/27 02:34:51 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026/08/27 02:34:52 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/08/27 02:34:54 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026/08/27 02:34:54 INFO mlflow.sklearn.utils: Logging the 500 best runs, no runs will be omitted.

🏃 View run traveling-sloth-34 at: http://localhost:5000/#/experiments/2/runs/0e823978f84e4a269c7b4fa95cf19cc5
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run nebulous-horse-850 at: http://localhost:5000/#/experiments/2/runs/314b1557b9ce4a7f8661a4446a82df84
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run stylish-doe-298 at: http://localhost:5000/#/experiments/2/runs/314ebcdc9a284288b6202b1c015775cb
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run learned-goat-659 at: http://localhost:5000/#/experiments/2/runs/a70a883a15bb4e6d9ccb3776fc476a4a
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run adaptable-goat-303 at: http://localhost:5000/#/experiments/2/runs/923827a5a10c410087bf0cfe9d483a3d
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run skillful-panda-453 at: http://localhost:5000/#/experiments/2/runs/aca605e97d8643caa219beccd99df8c6
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run worried-dove-541 at: http://localhost:5000/#/experiments/2/runs/d5ff6535596b40fe8593c5d611fa2115
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run enthused-robin-180 at: http://localhost:5000/#/experiments/2/runs/c500f6a6e4e74f0bb7efdbe933e90c5b
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run painted-pig-264 at: http://localhost:5000/#/experiments/2/runs/1b69a1ae2dd94b5a91b2ee91991ad866
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run bustling-gull-309 at: http://localhost:5000/#/experiments/2/runs/712474b510774dc8a56a18a325cd5405
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run stately-robin-412 at: http://localhost:5000/#/experiments/2/runs/c431e1fa931b485bb09131164338d0ca
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run masked-cow-568 at: http://localhost:5000/#/experiments/2/runs/3b79eaa8db5846258a7b88b1b9eb9749
🧪 View experiment at: http://localhost:5000/#/experiments/2
 Best Parameters: {'learning_rate': 0.2, 'max_depth': 3, 'n_estimators': 100}
 Best CV F1 Score: 0.9187
 Holdout Test F1 Score: 0.9250
🏃 View run Parent_GridSearch_XGBoost at: http://localhost:5000/#/experiments/2/runs/9f9dfd8aa1e840d3ada16342ba0fd724
🧪 View experiment at: http://localhost:5000/#/experiments/2

 All hyperparameter tuning experiments successfully logged to MLflow!

In [110]:
from mlflow.tracking import MlflowClient

# Initialize MLflow Client
client = MlflowClient(tracking_uri="http://localhost:5000")
model_name = "Phone_Price_Classification_model"

# Get all versions of the registered model sorted by version number
model_versions = client.search_model_versions(f"name='{model_name}'")
latest_version = max([int(mv.version) for mv in model_versions])

print(f"Loading latest registered model version: {latest_version}")

# Load the specific version using the version URI pattern
model_uri = f"models:/{model_name}/{latest_version}"
loaded_model = mlflow.pyfunc.load_model(model_uri)

Loading latest registered model version: 4

Downloading artifacts:   0%|          | 0/5 [00:00<?, ?it/s]

In [103]:
test = pd.read_csv('/home/butcher/projects/llm_wiki/experiments/test.csv')

In [104]:
test.columns

Index(['id', 'battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc',
       'four_g', 'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc',
       'px_height', 'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi'],
      dtype='object')

In [105]:
test = scaler.transform(test.iloc[:,1:])

In [106]:
test

array([[-0.4422551 ,  1.011314  ,  0.33114017, ..., -1.78870765,
         0.99128795, -1.02532046],
       [-0.90354259,  1.011314  , -1.25918898, ...,  0.55906285,
        -1.00878862, -1.02532046],
       [ 1.3024164 ,  1.011314  ,  1.55447029, ..., -1.78870765,
         0.99128795,  0.97530483],
       ...,
       [-0.1179837 , -0.98881258, -0.15819188, ...,  0.55906285,
        -1.00878862, -1.02532046],
       [ 0.67670961,  1.011314  , -1.25918898, ..., -1.78870765,
         0.99128795, -1.02532046],
       [ 0.07612243,  1.011314  , -1.25918898, ...,  0.55906285,
        -1.00878862,  0.97530483]], shape=(1000, 20))

In [113]:
pred = loaded_model.predict(test)

In [114]:
pred

array([2, 3, 2, 3, 1, 3, 3, 1, 3, 0, 3, 3, 0, 0, 2, 0, 2, 1, 3, 2, 1, 3,
       1, 1, 3, 0, 2, 0, 3, 0, 2, 0, 3, 0, 1, 1, 3, 1, 2, 1, 1, 2, 0, 0,
       0, 1, 0, 3, 1, 2, 1, 0, 2, 0, 3, 0, 3, 1, 0, 3, 3, 3, 0, 1, 1, 1,
       2, 3, 1, 2, 1, 2, 2, 3, 3, 0, 2, 0, 1, 3, 0, 3, 3, 0, 3, 0, 3, 1,
       3, 0, 1, 1, 2, 1, 2, 2, 0, 2, 1, 3, 1, 0, 0, 3, 0, 2, 0, 1, 2, 3,
       3, 3, 1, 3, 3, 3, 3, 2, 3, 0, 0, 3, 2, 1, 2, 0, 3, 2, 2, 2, 0, 2,
       2, 1, 3, 1, 1, 0, 3, 2, 1, 2, 1, 3, 2, 3, 3, 3, 2, 3, 2, 3, 1, 0,
       3, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 1, 0, 3, 0, 0, 0, 2, 1, 0, 1,
       0, 0, 1, 2, 1, 0, 0, 1, 1, 2, 2, 1, 0, 0, 0, 1, 0, 3, 1, 0, 2, 2,
       3, 3, 1, 2, 3, 2, 3, 2, 2, 1, 0, 0, 1, 3, 0, 2, 2, 3, 0, 2, 0, 3,
       2, 3, 3, 1, 0, 1, 0, 3, 0, 1, 0, 2, 2, 1, 3, 1, 3, 0, 3, 1, 2, 0,
       0, 2, 1, 3, 3, 3, 1, 1, 3, 0, 0, 2, 3, 3, 1, 3, 1, 1, 3, 2, 1, 2,
       3, 3, 3, 1, 0, 0, 2, 3, 1, 1, 3, 2, 1, 3, 0, 1, 2, 0, 0, 3, 2, 3,
       3, 2, 1, 3, 3, 2, 3, 1, 2, 1, 2, 0, 2, 3, 1, 0, 0, 3, 0, 3, 0, 1,
       2, 0, 2, 3, 1, 3, 2, 2, 1, 2, 0, 0, 0, 1, 3, 2, 0, 0, 0, 3, 2, 0,
       2, 3, 1, 2, 2, 2, 3, 1, 3, 3, 2, 2, 2, 3, 3, 0, 3, 0, 3, 1, 3, 1,
       2, 3, 0, 1, 0, 3, 1, 3, 2, 3, 0, 0, 0, 0, 2, 0, 0, 2, 2, 1, 2, 2,
       2, 0, 1, 0, 0, 3, 2, 0, 3, 1, 2, 2, 1, 2, 3, 1, 1, 2, 2, 1, 2, 0,
       1, 1, 0, 3, 2, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 2, 2, 3, 2, 3, 0, 3,
       0, 3, 0, 1, 1, 0, 2, 0, 3, 2, 3, 3, 1, 3, 1, 3, 1, 2, 2, 0, 1, 2,
       1, 1, 0, 0, 0, 1, 2, 1, 0, 3, 2, 0, 2, 2, 0, 0, 3, 1, 1, 0, 2, 3,
       3, 0, 3, 0, 2, 3, 2, 3, 0, 2, 0, 2, 2, 0, 1, 1, 0, 0, 1, 1, 1, 3,
       3, 3, 2, 3, 1, 2, 2, 3, 3, 3, 2, 0, 2, 1, 2, 2, 1, 0, 2, 2, 0, 0,
       0, 3, 1, 0, 2, 2, 2, 0, 3, 1, 2, 2, 1, 3, 0, 2, 3, 0, 1, 1, 3, 3,
       2, 1, 2, 3, 2, 0, 3, 1, 2, 0, 3, 3, 1, 3, 2, 2, 3, 0, 1, 2, 3, 1,
       3, 2, 3, 1, 1, 0, 0, 3, 1, 0, 3, 2, 3, 3, 0, 3, 3, 3, 2, 3, 3, 1,
       2, 1, 2, 3, 3, 1, 0, 1, 1, 2, 2, 2, 0, 0, 2, 2, 3, 2, 0, 2, 1, 3,
       3, 0, 1, 3, 0, 2, 1, 1, 0, 0, 2, 1, 0, 1, 1, 2, 2, 0, 2, 2, 1, 0,
       3, 0, 0, 3, 2, 0, 0, 0, 0, 0, 3, 0, 3, 1, 3, 1, 1, 3, 2, 0, 1, 0,
       3, 2, 2, 2, 0, 3, 0, 2, 0, 2, 0, 0, 1, 1, 1, 2, 1, 3, 1, 3, 2, 2,
       1, 3, 2, 0, 2, 2, 0, 3, 3, 0, 2, 1, 1, 2, 0, 3, 2, 0, 3, 2, 3, 0,
       0, 3, 0, 2, 2, 3, 2, 2, 2, 2, 1, 2, 3, 0, 1, 0, 1, 2, 1, 0, 0, 1,
       0, 0, 3, 0, 1, 2, 0, 1, 0, 1, 3, 0, 3, 2, 3, 0, 0, 1, 2, 2, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 3, 3, 0, 3, 1, 1, 3, 0, 1, 0, 2, 2, 0, 3, 1,
       0, 3, 1, 1, 0, 3, 3, 3, 2, 3, 0, 3, 2, 0, 0, 0, 3, 3, 2, 0, 2, 1,
       3, 0, 0, 2, 2, 0, 3, 1, 2, 1, 1, 1, 3, 1, 1, 1, 2, 1, 0, 2, 2, 0,
       2, 0, 0, 0, 0, 2, 3, 3, 3, 0, 1, 2, 1, 1, 0, 0, 2, 1, 0, 2, 0, 3,
       2, 2, 1, 2, 0, 2, 1, 3, 0, 0, 3, 2, 3, 0, 0, 2, 3, 3, 1, 3, 2, 1,
       0, 0, 3, 3, 1, 3, 0, 0, 0, 2, 2, 1, 2, 0, 3, 2, 1, 2, 3, 3, 0, 1,
       1, 2, 1, 2, 2, 0, 1, 3, 1, 1, 3, 0, 2, 3, 2, 1, 1, 1, 3, 3, 0, 2,
       3, 0, 2, 3, 2, 2, 2, 3, 2, 0, 1, 2, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1,
       0, 1, 3, 1, 0, 1, 2, 3, 1, 0, 0, 3, 2, 2, 3, 0, 3, 2, 2, 1, 3, 0,
       1, 3, 1, 1, 1, 2, 3, 2, 0, 3, 0, 2, 3, 0, 3, 1, 3, 3, 1, 0, 2, 3,
       1, 0, 2, 1, 2, 1, 2, 0, 2, 2, 0, 2, 3, 2, 3, 0, 2, 1, 1, 2, 2, 3,
       3, 0, 2, 1, 2, 1, 3, 1, 1, 3, 0, 1, 0, 0, 3, 3, 2, 0, 0, 0, 0, 3,
       2, 3, 3, 0, 0, 2, 1, 0, 2, 2])